# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20171124_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_info',
            field=models.CharField(blank=True, default='image info', max_length=30, null=True),
        ),
    ]
