# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171127_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='category',
        ),
    ]
