# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20171127_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='tag', max_length=30),
        ),
    ]
