# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 02:27
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20171208_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpost',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedpost',
            name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TaggedPost',
        ),
    ]
